### ISSUE TITLE
The video is missing. .. how does it work ? Is it just like the other ones  ?

### ISSUE THREAD

**Issue by minanagehsalalma** [hasanfirnas/symbiote#1]

**Comment by hasanfirnas** [comment]
s bro i uploded the video

**Comment by minanagehsalalma** [comment]
@404-ghost yeah it's just like the other ones.

Who the  ..... would click allow ?

Also why it's pics not a stream of the cam ?

**Comment by swagkarna** [comment]
macha serveo website is down . so serveo tunnel wont work
