### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bennetho** [hasanfirnas/symbiote#4]
Hey its not workig

**Comment by hasanfirnas** [comment]
bro, check it out now,
and select "localhost.run" as Server. ✌️

**Comment by bennetho** [comment]
RANDOM localhost URL !!] 
-------------------------------

	 wait for few second.....
The authenticity of host 'ssh.localhost.run (107.22.191.251)' can't be established.
RSA key fingerprint is SHA256:FV8IMJ4IYjYUTnd6on7PqbRjaZf4c1EhhEBgeUdE94I.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Traceback (most recent call last):
  File "/home/linux/Downloads/symbiote/symbiote.py", line 290, in <module>
    selectServer(port)
  File "/home/linux/Downloads/symbiote/symbiote.py", line 179, in selectServer
    randomServeo(port)
  File "/home/linux/Downloads/symbiote/symbiote.py", line 156, in randomServeo
    url=(f"{f.read().split(',')[1]}")
IndexError: list index out of range


still not working

**Comment by hasanfirnas** [comment]
Sorry to say it, This program works perfectly in Linux 🐧, But not in Termux bro.

**Comment by bennetho** [comment]
Am using Linux.  Parrot os operating system

**Comment by hasanfirnas** [comment]
My apologies for the late response, the script now works as it should.
